FROM 32bit/ubuntu:14.04
MAINTAINER Sean Chuang <sean_chuang@htc.com>

RUN apt-get -y update

# dependencies
RUN apt-get update && apt-get install -y \
  vim \
  curl \
  git \
  protobuf-compiler \
  python-dev \
  python-pip \
  wget \
  libopencv-dev \
  build-essential \
  cmake \
  libgtk2.0-dev \
  pkg-config \
  python-numpy \
  libdc1394-22 \
  libdc1394-22-dev \
  libjpeg-dev \
  libpng12-dev \
  libtiff4-dev \
  libjasper-dev \
  libavcodec-dev \
  libavformat-dev \
  libswscale-dev \
  libxine-dev \
  libgstreamer0.10-dev \
  libgstreamer-plugins-base0.10-dev \
  libv4l-dev \
  libtbb-dev \
  libqt4-dev \
  libfaac-dev \
  libmp3lame-dev \
  libopencore-amrnb-dev \
  libopencore-amrwb-dev \
  libtheora-dev \
  libvorbis-dev \
  libxvidcore-dev \
  x264 \
  v4l-utils \
  unzip \
  tmux

# put vision face in the docker
ADD files /opt/files

# build opencv lib
RUN cd /opt/files && ./build_opencv.sh

# cleanup
RUN apt-get clean && rm -rf /tmp/* /var/tmp/*