FROM opencv/32bit
MAINTAINER Sean Chuang <sean_chuang@htc.com>

# add flask-server folder
RUN pip install Flask pymongo simplejson
#ADD flask-server /opt/flask-server

# add mongodb .so to /usr/lib
ADD files/mongodb /opt/mongodb
RUN mv /opt/mongodb/* /usr/lib/
RUN ldconfig

# run server
EXPOSE 8888
WORKDIR /opt/flask-server
CMD ["python", "server.py"]

# cleanup
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
